---

SUPPORTED_OS:
  - { distribution: OracleLinux, major_version: '9' }
  - { distribution: RedHat, major_version: '9' }
  - { distribution: OracleLinux, major_version: '10' }
  - { distribution: RedHat, major_version: '10' }


MIN_RU_VERSION_ON_MAJOR_VERSION: {}

MIN_MEM_MB: 8000
MIN_VCPU: 2
MIN_SWAP_MB: 16384

RESPONSE_FILE_SCHEMA_VERSION: 'CHANGE_ME_26AI_SCHEMA_VERSION'

RU_VERSION: '26.6.0'
BASE_VERSION: '26.3.0'
RU_NUMBER_INDEX: 2

ORA_INVENTORY: /u01/app/oraInventory
GRID_HOME_PATTERN: /u01/app/{RU_VERSION}/grid
GRID_BASE: /u01/app/grid
DB_HOME_PATTERN: /u01/app/oracle/product/{RU_VERSION}/oracle
DB_BASE: /u01/app/oracle


GRID_MEDIA:
  path: /mnt/nfs/nfsshare/ora_binaries/golden_images/23.26.3/grid/p39581618_230000_Linux-x86-64.zip
  sha256: ''
DB_MEDIA:
  path: /mnt/nfs/nfsshare/ora_binaries/golden_images/23.26.3/oracle/
  sha256: ''
